config/routes.rb
Rails.application.routes.draw do
  get 'timejobs/index'
  resources :job
  post 'job/create' => 'job#create'
  post 'job/:id/update' => 'job#update'
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  get '/' => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
    validates :user_id, {presence: true}
    validates :start_time,{presence: true}
    validates :end_time, {presence: true}
    validates :money, {presence: true}
    validates :people, {presence: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys:[:name]) 
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/job_controller.rb
class JobController < ApplicationController

  def index
    @jobs = Work.all
  end

  def new
    @job = Work.new
  end

  def show
    @job = Work.find(params[:id])
  end

  def create
    @job = Work.new(job_parameter)
    if @job.save
      redirect_to job_index_path
    else
      render 'new'
    end
  end

  def destroy
    @job = job.find(params[:id])
    @job.destroy
    redirect_to job_index_path, notice:"削除しました"
  end

  def edit
    @work = Work.find(params[:id])
  end

  def update
    @job = Work.find(params[:id])
    if @job.update(job_parameter)
      redirect_to job_index_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  private

  def job_parameter
    params.permit(:start_time, :end_time, :money, :people).merge(user_id: current_user.id)
  end

end

app/controllers/timejobs_controller.rb
class TimejobsController < ApplicationController
  def index
    @jobs = Work.all.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_helper.rb
module JobHelper
end

app/helpers/timejobs_helper.rb
module TimejobsHelper
end

app/views/home/index.html.erb
<div class="main">
    <h1>バイト管理アプリ</h1>
    <p>シフトを管理しよう</p>
</div>

app/views/job/edit.html.erb
<%= form_with(model: @work , local: true) do |form| %>
    <div class="main container">
        <div class="time">
            <%= form.label :start_time %>
            <%= form.datetime_select :start_time, class:"mb-5" %>
        </div>
        <div class="time">
            <%= form.label :end_time %>
            <%= form.datetime_select :end_time, class:"mb-5" %>
        </div>
    
        <div class="money">
            <%= form.label :money %>
            <%= form.text_field :money%>
        </div>
    
        <div class="people">
            <%= form.label :people %>
            <%= form.text_field :people%>
        </div>
    
        <div class="submit">
            <%= form.submit %>
        </div>
    </div>
<% end %>

app/views/job/index.html.erb
<p id="notice"><%= notice %></p>

<br>
<div class="main">
    <div class="container">
    <h1>バイト表</h1>
    <%= link_to 'バイト依頼', new_job_path ,class:"btn btn-primary"%>
        <%= month_calendar events: @jobs do |date, jobs| %>
            <%= date.day %>

            <% jobs.each do |job| %>
                <div>
                    <%= link_to job.people, job_path(job) %>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/job/new.html.erb
<%= form_with(url:job_create_path , local: true) do |form| %>
<div class="main container">
    <h1>新規バイト</h1>
    <div class="time">
        <%= form.label :開始 %>
        <%= form.datetime_select :start_time, class:"mb-5" %>
    </div>

    <div class="time">
        <%= form.label :終了 %>
        <%= form.datetime_select :end_time, class:"mb-5" %>
    </div>

    <div class="money">
        <%= form.label :時給 %>
        <%= form.text_field :money%>円
    </div>

    <div class="people">
        <%= form.label :人数 %>
        <%= form.text_field :people%>人
    </div>

    <div class="submit">
        <%= form.submit "発行",class:"btn btn-secondary col-3"%>
    </div>
</div>
<% end %>

app/views/job/show.html.erb
<div class="main">
    <h1>Job#show</h1>
    <p id="notice"><%= notice %></p>

    <p>
        <strong>時給</strong>
        <%= @job.money.to_s + "円" %>
    </p>

    <p>
        <strong>開始</strong>
        <%= @job.start_time.strftime("%Y-%m-%d %H:%M") %>
    </p>

    <p>
        <strong>終了</strong>
        <%= @job.end_time.strftime("%Y-%m-%d %H:%M") %>
    </p>

    <p>
        <strong>人数</strong>
        <%= "あと"+ @job.people.to_s + "人" %>
    </p>

    <%= link_to 'Edit', edit_job_path(@job) %> |
    <%= link_to 'Back', job_index_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job+</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= link_to "job+" , "/" ,class:"header-logo"%>
      <ul>
        <% if user_signed_in?%>
          <li><%= link_to "ログアウト", destroy_user_session_path ,class:"header-list",data: { confirm: 'ログアウトしますか？' }%></li>
          <li><%= link_to "バイト依頼", timejobs_index_path ,class:"header-list"%></li>
          <li><%= link_to "新規バイト", new_job_path ,class:"header-list"%></li>
          <li><%= link_to "バイト表" , job_index_path ,class:"header-list"%></li>
          <li><%= current_user.name%></li>
        <% else %>
          <li><%= link_to "ログイン" , new_user_session_path ,class:"header-list"%></li>
          <li><%= link_to "新規登録" , new_user_registration_path ,class:"header-list"%></li>
        <% end %>
      </ul>
    </header>
    <%= yield %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/timejobs/index.html.erb
<div class="main container">
    <h1>Timejobs#index</h1>
    <% @jobs.each do |job|%>
        <div class="time-job">
            <%= link_to job.start_time.strftime("%m-%d %H:%M")+ " ~ " +job.end_time.strftime("%H:%M"), job_path(job),class:"btn btn-success col-3"%>
        </div>
    <% end %>
</div>